# Generated by Django 4.2.4 on 2023-09-05 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0003_alter_tarea_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
