# Generated by Django 4.2.4 on 2023-09-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0008_remove_tarea_observaciones_observaciones_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observaciones',
            new_name='Observacion',
        ),
    ]
