# Generated by Django 4.2.4 on 2023-09-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0009_rename_observaciones_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observacion',
            old_name='text',
            new_name='texto',
        ),
    ]
