# Generated by Django 5.0 on 2023-12-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0012_alter_tarea_asignada_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='observaciones',
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
