# Generated by Django 5.0 on 2023-12-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0016_remove_observacion_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='observaciones',
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
