# Generated by Django 5.0 on 2023-12-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0018_observacion_tarea_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='asignada_a',
        ),
    ]
