# Generated by Django 5.0 on 2023-12-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0020_remove_tarea_observaciones_tarea_asignada_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
