# Generated by Django 5.0 on 2023-12-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0022_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Observacion',
        ),
    ]
