# Generated by Django 5.0 on 2023-12-19 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tareas', '0023_alter_tarea_observaciones_delete_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tareas.tarea')),
            ],
        ),
    ]
